name = input("Enter your name: ")
address = input("Enter your address: ")
city = input("Enter your city: ")
state = input("Enter your state: ")
zip = input("Enter you zip code: ")
phone = input("Enter you phone number: ")
print(name)
print(address)
print(city, state, zip)
print(phone)
